[package]
name = "dc"
version = "0.1.0"
authors = ["Ferenc Nagy <nagy.ferenc.jr@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
num-bigint = "0.2.6"
num-traits = "*"